### ISSUE TITLE
Cloning 247-main

### ISSUE THREAD

**Issue by coltoncasto** [hassonlab/247-main#10]
Not sure why but it was not allowing me to connect to github to clone the repo that you wanted us to... It is saying that a don't have the correct access rights (see attachment). I think I did all the steps in the wiki... but I found the ssh key thing pretty confusing so I could have done something wrong there. I tried to do some reading but it still didn't make much sense. I was able to clone stuff from git before when I was working with Harsha's code, not sure why this would be different.

Sorry for not messaging sooner, I kinda forgot about this until earlier tonight. 

<img width="549" alt="Screen Shot 2021-01-27 at 12 27 36 AM" src="https://user-images.githubusercontent.com/56043228/105947376-00557380-6037-11eb-9165-e98f40a4d3c9.png">

**Comment by hvgazula** [comment]
try https instead of ssh and see if it works. `git clone https://github.com/hassonlab/247-main.git`

**Comment by coltoncasto** [comment]
That worked. Thanks.
