### ISSUE TITLE
Matlab does not run on tigercpu or tigergpu

### ISSUE THREAD

**Issue by manojneuro** [hassonlab/247-main#12]
After spending many hours trying to get everything working, I found out that matlab jobs cannot be scheduled on tigercpu or tigergpu. Only if the code is gpu compatible can the code be run on tigergpu. So all ECoG preprocessing must be done on other clusters.

You all might already know this though.

**Comment by hvgazula** [comment]
https://researchcomputing.princeton.edu/matlab
![image](https://user-images.githubusercontent.com/9400767/106954041-3367c900-6701-11eb-9ea9-3587aa8499e2.png)

**Comment by hvgazula** [comment]
> After spending many hours trying to get everything working, I found out that matlab jobs cannot be scheduled on tigercpu or tigergpu. Only if the code is gpu compatible can the code be run on tigergpu. So all ECoG preprocessing must be done on other clusters.
> 
> You all might already know this though.

Let's rewrite the preprocessing in Python ;)

**Comment by manojneuro** [comment]
Luckily I now only have to change some folder paths to get going on another cluster. Back to our old friend scotty.

**Comment by hvgazula** [comment]
> Luckily I now only have to change some folder paths to get going on another cluster. Back to our old friend scotty.

ohoo
