### ISSUE TITLE
rsync issues

### ISSUE THREAD

**Issue by hvgazula** [hassonlab/247-main#3]
@zkokaja In my haste to unlink the data from conversations-car on tiger, I ended up deleting 625 and when I tried running `make 625-sync` there's some error. Please advise if I am missing anything.

![Screen Shot 2021-01-05 at 12 35 12 PM](https://user-images.githubusercontent.com/9400767/103679127-77c14700-4f52-11eb-8cfc-f070fe13349a.png)

**Comment by hvgazula** [comment]
nvm i think i shud do `scp` first. please verify.

**Comment by hvgazula** [comment]
`rsync` there was a typo in the make target. thanks.

**Comment by hvgazula** [comment]
the issue remains
![Screen Shot 2021-01-05 at 1 10 41 PM](https://user-images.githubusercontent.com/9400767/103682858-6b8bb880-4f57-11eb-9413-e0dbe7198377.png)

**Comment by zkokaja** [comment]
Can you clarify what was the typo? Did you google the error?

**Comment by zkokaja** [comment]
I see the 625 files on Tiger that you own. What is missing?

**Comment by zkokaja** [comment]
Yea I saw the error but i'm not familiar with it. Did google give more info? Is everything synced?

**Comment by hvgazula** [comment]
That's the part I am unsure of 'if everything synced?'

**Comment by zkokaja** [comment]
Ok thanks. I created 625/ and 676/ on scotty and did `make sync-625 and sync-676` without any issues. I updated the Makefile paths.

**Comment by hvgazula** [comment]
If it didn't throw a `rsync error` then I guess it has to do with permissions. Maybe.
